### ISSUE TITLE
Domoticz version?

### ISSUE THREAD

**Issue by magnusheino** [moroen/IKEA-Tradfri-plugin#10]
Hi. What domoticz version are you using? Using the latest beta, the plugin isn't listed in the add hardware dialog. Using latest stable, the plugin is there but nothing happens when I try to add it. There are no input fields for ip, key etc... is that supposed to be there?

**Comment by magnusheino** [comment]
Hm.. some chome issue. I was able to add it using firefox. I get this error though:

` 2017-09-06 22:39:21.017 (IKEA Tradfri) Initialized version 1.0.0, author 'moroen'
2017-09-06 22:39:21.072 PluginSystem: Starting I/O service thread.
2017-09-06 22:39:21.123 (IKEA Tradfri) Connected successfully to: 192.168.1.153
2017-09-06 22:39:21.123 (IKEA Tradfri) Received: b'{"action": "clientConnect", "version": "0.3", "status": "Ok"}'
2017-09-06 22:39:22.080 (IKEA Tradfri) Received: b'{"action": "setConfig", "status": "Failed", "error": "Connection timed out"}'
2017-09-06 22:39:22.081 (IKEA Tradfri) Command setConfig failed with error: Connection timed out.
2017-09-06 22:39:22.081 (IKEA Tradfri) {'error': 'Connection timed out', 'action': 'setConfig', 'status': 'Failed'} `

**Comment by moroen** [comment]
It appears that the the service (COAP-adaptor) times out when trying to connect to the IKEA Gateway, while communication between the plugin and adaptor appears to be working. Are you sure you have specified the correct gateway IP on the plugin config-page? 

The master branch should work with the latest stable. 

If you're using latest beta, you have to use the domoticz/python-enabled branch, as python has been temporarily disabled in the developement branch, and the developement-branch of the plugin.

**Comment by magnusheino** [comment]
Yes, ip is correct. It's working with pytradfri standalone and from Home Assistant. I did have to power cycle the gateway to get pytradfri working the first time though.  It threw RequestTimeout exceptions (IKEA app was still working). Never tried if pytradfri was still working after I installed your plugin. I'll try with another reset of the gateway, or else try to remove the dust from my long ago python coding adventures ;)

**Comment by moroen** [comment]
Just one more thing, have you made sure that the coap-library and coap-client are working? The pytradfri library supports both async (aiocoap) and sync (coap-client) communication, the plugin requires the coap-client version. Does coap-client work from the command line?

**Comment by magnusheino** [comment]
Thank you! libcoap was not working on my raspberry pi on which I run domoticz. Now it is working, and I can control everything from domoticz. Great! :-) Are the soon to be released everythere RGB lightbulbs that pytradfri supports already working in this plugin too, or is there something that needs to be done? Once again, great plugin! :+1:
