### ISSUE TITLE
IKEA-Tradfi-plugin kills Homebridge

### ISSUE THREAD

**Issue by felix63** [moroen/IKEA-Tradfri-plugin#105]
I have identified a very annoying problem.

My config:
Domoticz Version: 2020.2 running on RPi 3+ with the following plugins:
- IKEA-Tradfri (version 0.9.1)
- Synology
- Mi-Flora

ATV as Homekit Hub
Philips Hue bridge
Raspberry PI's with all kinds of smart stuff connected
Homebridge v1.1.1 with the following plugins:
- Homebridge Config UI X
- Homebridge Camera FFmpeg
- Homebridge Ring
- Homebridge Samsung Tizen
Hoobs v3.2.6
- Homebridge Alexa
- Homebridge eDomitcz

I also have an Ikea Trådfri. When I start the Trådfri the connection between Homebridge & Hoobs to Homekit is lost. I can verify this using Discovery monitoring Bonjour traffic. Both Homebridge and Hoobs are running normally and show no error messages. When I unplug the Trådfri Homebridge communication is restored. But does this mean I have to dump my Trådfri?

I found that when I deactivate the IKEA Tradfri Plugin connectivity is restored. So what's happening and more importantly (well, not really) can it be fixed? For now I am relieved that I have finally found something and that my IKEA Trådfri is not a write off... but at a certain point I will want to see the IKEA devices in my Domoticz setup!

**Comment by moroen** [comment]
I have posted a request for further clarification on your post to the plugin thread on the domoticz forum!

**Comment by felix63** [comment]
I’ve responded! Thanks for looking Into this!
    	
    	

    	
    
  




On Wed, Jul 1, 2020 at 9:36 PM +0200, "moroen" <notifications@github.com> wrote:















I have posted a request for further clarification on your post to the plugin thread on the domoticz forum!

**Comment by moroen** [comment]
Have you been able to determine if it's the plugin that kills the connection?

**Comment by felix63** [comment]
No. It’s not. It seems to be some underlying network problem. I resolved it by plugging the tradfri in a different place in the network. I think it has the same ip but still now it works. It is really driving me nuts. I continue to have network related errors in my domoticz log but also between homebridge and Domoticz.




Verstuurd vanaf mijn iPad

**Comment by moroen** [comment]
Ok, hope you'll sort it out! Closing this issue.
