### ISSUE TITLE
No longer turning the lights on. 

### ISSUE THREAD

**Issue by Dutchy-79** [moroen/IKEA-Tradfri-plugin#113]
When turning the lights on I get this error.
```
Tradfri/plugin.py', function onCommand
2020-09-02 12:10:47.198 Error: (Ikea Tradfri) ----> Line 615 in '/home/pi/domoticz/plugins/IKEA-Tradfri/plugin.py', function onCommand
```
When checking the list like Readme says they are there. 
Also with ikea remote and app the lights work.

**Comment by SBergers** [comment]
I have the exact same thing with just one of the devices in my Ikea-environment.
I have 3 lights: Buitenlamp Achter, Servieskast and TV-Verlichting.
The TV-Verlichting is a aomplifier for spots on a closet, which is lead through the Servieskast.
However, i can control everything from the ikea app, when trying from domoticz all lights work accept the Servieskast.
I get these errors in log:

2020-09-15 13:14:24.752 Status: User: Sander initiated a switch command (123/Servieskast/On)
2020-09-15 13:14:24.768 Error: (IKEA Tradfri) 'onCommand' failed 'KeyError'.
2020-09-15 13:14:24.768 Error: (IKEA Tradfri) ----> Line 703 in '/home/pi/domoticz/plugins/IKEA-Tradfri/plugin.py', function onCommand
2020-09-15 13:14:24.768 Error: (IKEA Tradfri) ----> Line 624 in '/home/pi/domoticz/plugins/IKEA-Tradfri/plugin.py', function onCommand

**Comment by Bolten88** [comment]
Since today the switches react very bad or not at all. But i do not see any errors in the log. When i click to turn on a light just nothing is happening. This morning i saw in the IKEA app that there were updates installed. Did this broke the plugin?

**Comment by basrieter** [comment]
Noticed the same. But there are not errors in the logfile. So this seems to be a new and different issue.

**Comment by bigus19** [comment]
Hello,
I have also issue with lights, but some different. I have 4 bulbs from Ikea. When I turn on/off ONE of them - this ONE bulb works OK. But after that any other bulb don't work with Domoticz... **but don't work only for ~45 seconds..**. After that time I can turn on/off another bulb and the error repeats. It looks like a delay is triggered and the gate doesn't accept any new commands for this time.

**Comment by basrieter** [comment]
Check https://github.com/moroen/IKEA-Tradfri-plugin/issues/114

**Comment by moroen** [comment]
Handled in the latest master, closing issue.
