### ISSUE TITLE
Readme has typo in cd domoticz/Plugins/IKEA-Tradfri

### ISSUE THREAD

**Issue by Dutchy-79** [moroen/IKEA-Tradfri-plugin#119]
Hi,

Readme says cd domoticz/Plugins/IKEA-Tradfri a few times though the Plugins folder doesn't have a capitol P its just p

cd domoticz/plugins/IKEA-Tradfri

**Comment by moroen** [comment]
Fixed in the latest master. Thanks for pointing this out! Closing issue.
