### ISSUE TITLE
Support for different bulb configurations

### ISSUE THREAD

**Issue by moroen** [moroen/IKEA-Tradfri-plugin#12]
Need to find a way to know if a bulb is dimmable, has settable WB etc.

**Comment by moroen** [comment]
Added support for different bulb properties. On startup, read devices.ini, which defines the properties of the bulbs. If a bulb is not in the file, a default entry will be added.

**Comment by mo8Zomo0** [comment]
cool. yes, that was also my though, to have a DB. I have to check it out.
