### ISSUE TITLE
Switch not updated

### ISSUE THREAD

**Issue by Rednas79** [moroen/IKEA-Tradfri-plugin#123]
When i press on a switch (hardware switch, link to show what switch i m using https://www.ikea.com/nl/nl/p/tradfri-draadloze-dimmer-wit-70408595/) to turn on or off an walloutlet, I dont see the switch updated in Domoticz

When i click in Domoticz its working and updated at the same time.

Running Domoticz 2020.2 and IKEA Tradfri Plugin - version 0.10.1

**Comment by moroen** [comment]
You need to set Monitor changes to poll, and even then, there will be a delay (polling-interval) before the switch gets updated in domoticz. A short polling interval will make domoticz more responsive in regard of updating the status of the switch, but to short an interval tends to freeze the gateway.

**Comment by Rednas79** [comment]
ok check, didnt have the option enabled.
Thanks it works.
