### ISSUE TITLE
Disappearing Devices

### ISSUE THREAD

**Issue by RDols** [moroen/IKEA-Tradfri-plugin#130]
I'm using the plugin to interface my Furtur curtains to domoticz. I general this works fine. But it happened a few the plugin deletes all te devices and adds them again. Most likely after a update of the ikea hub. This is pretty unpractical, scripts stop working, and devices are not visible anymore. After such event i have to rename and add them to the active devices in domoticz.

Is it possible to make the deletion of devices a optional?

regards,
  Richard

**Comment by moroen** [comment]
Is #127 relevant for your situation?

**Comment by RDols** [comment]
Yes. I'm not on the latest version of library and plugin. Look pretty simular. Only difference is I noticed it only after an update on the firmware of tradfri hub. I will try if this works, but will take month before i know. I close the ticket, and will reopen #127 when needed. 

Thanks.
