### ISSUE TITLE
Increasing CPU loop

### ISSUE THREAD

**Issue by WilcoVertegaal** [moroen/IKEA-Tradfri-plugin#131]
Running the plugin on a Raspberry Pi (model 2B), I notice the tradfri command to take up a lot of CPU. The funny thing is that it builds from almost 0 to like 60% in half a minute, then drops all the way down to almost 0, and then the whole thing repeats itself. Is there anything I can do to stop these high CPU loads?

**Comment by moroen** [comment]
@WilcoVertegaal 

Sorry for the late reply!

I'm not seeing this, could you provide a bit more information? What is the plugin doing when the CPU increases? Getting devices? Polling for changes? Switching devices? Just idling?

**Comment by WilcoVertegaal** [comment]
@moroen

Thanks for the reply. Actually I think the issue might have been caused by running tradfri as a service. It is no longer needed I think? Could that be correct? If I stop the service, the high CPU load disappears and the plugin still works.

So the issue would be "Could you please update the documentation" :-)

Thanks for all the hard work. Much appreciated!
