### ISSUE TITLE
Initialized version 0.11.0, author 'moroen'

### ISSUE THREAD

**Issue by dbgnu76** [moroen/IKEA-Tradfri-plugin#133]
Why is it Initialized version 0.11.0, author 'moroen'  ,,shouldnt it be 0.10.6 ?

Nothing works after update :(

**Comment by dbgnu76** [comment]
I solved it ,, 
i removed the whole ikea directory ,,and reinstall ,,,

**Comment by moroen** [comment]
FYI, 0.11.0 is currently in the development branch, 0.10.6 in master. The versions in the development branch should normally work, but no guarantees. 0.11.x currently needs the development version of tradfricoap as well...
