### ISSUE TITLE
Rounding (issue 107) seems to have returned. 

### ISSUE THREAD

**Issue by JohnnyJohnnySE** [moroen/IKEA-Tradfri-plugin#136]
I recently upgraded everything to latest version and I noticed my automation was a bit off, and upon closer inspection it seems to be an old issue that has returned (Issue 107) the rounding seems to be off for dimmers so if you put 50% in domoticz, the device reports 49% if you query the device, which makes scripts fail that is checking what % a device is at.

**Comment by moroen** [comment]
Fixed in 0.10.7, just pushed to the master branch... It appears to work as it should now, but feel free to reopen if needed...
