### ISSUE TITLE
tradfri.tac Unhandled error in Deferred

### ISSUE THREAD

**Issue by m0rph13** [moroen/IKEA-Tradfri-plugin#15]
Hi.
Can connnect to my Trådfri using coaplib or through pytradfri.
Have added IKEA-Tradfri-plugin to Domoticz and all my lights show up (although there seem to be some encoding issue at hand :) )

When starting tradfri.tac
I see the following output:
`pi@raspberrypi ~/domoticz/plugins/IKEA-Tradfri $ python3 tradfri.tac
IKEA-tradfri COAP-adaptor version 0.3 started (command line)!
Waiting for connection
Unhandled error in Deferred:

`

**Comment by moroen** [comment]
Unhandled errror in Deferred on startup, usually means there another process using the 1234-port, another instance of tradfri.tac already running?

The latest commit should give a more informative error message if this is the case...

**Comment by m0rph13** [comment]
Works, thanks!
