### ISSUE TITLE
Error in annouce:

### ISSUE THREAD

**Issue by mo8Zomo0** [moroen/IKEA-Tradfri-plugin#17]
Hi!

I see "Error in annouce:" messages and communication does not work. 
The fix for me is to powercycle the hub.
Currently the For some time the combination of Trådfri, Domoticz and this plugin runs very unstable.

Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:
Error in annouce:

**Comment by moroen** [comment]
There are suspicions on the net that the current firmware of the gateway might have some kind of memory leak, as it seems to hang after a while, the more lights and the more requests the sooner it seems to hang. The way observations are being done, using polling, appears to "kill" the gateway. I'm working on a better way to do observations, but struggling to make it reliable.

Until then, if you don't really need domoticz to be notified when a lights gets switched using a remote, I would recommend to update to latest the version of the plugin, and disable "Observe changes". I have disabled observations on my own system, and haven't had the gateway hanging for quite some days now... Before I needed to cycle the gateway power about every second day...

**Comment by mo8Zomo0** [comment]
can you make an option to disable other functionalities then the lights, like the group and if you enabled more. My feeling is that this is the main trouble maker. Though I like to have full support, I think it became worse after these features were added.

**Comment by moroen** [comment]
Have you tried to disable observations? I'm curious to see if anyone else have the same experience as my own regarding stability. The main focus at the moment is the aiocoap version, but an option to disable groups should be implemented!

**Comment by moroen** [comment]
Added a new commit, with the option for turning off "Groups as devices"

**Comment by magnusheino** [comment]
I have huge stability issues, my setup includes 21 lamps. Observations on or off doesnt matter. Gayeway needs to be power-cycled within hours :-(

**Comment by moroen** [comment]
Strange, with observations off, the only connections from the plugin/adapter to the gateway should be when switching lights.

Have you tried disabling the adapter/plugin for a while, just to make sure that the gateway doesn't hang because of something else?

Could you also check to make sure there are no coap-client requests running/hanging in the background?

'''
$ ps -aux | grep -i coap-client
'''

**Comment by mo8Zomo0** [comment]
I disabled the group and I still have the issue, and also here power cycling would help.
I restart every 12 hours, but thats not enough.
 
I did not test it without the observations function though.


If I manually run a coap client it at least gets result back. no coap client hanging btw.

**Comment by moroen** [comment]
I really recommend turning of observations, it more or less hammers the gateway with requests, since it's done using polling, one request per light and group every two seconds... A better way for observations is really needed, but until observations using aiocoap works reliably, I don't see how...

**Comment by magnusheino** [comment]
To make sure I don't have any running/hanging requests, I turned off observations, updated this plugin to current master, turned on "Add groups as devices" and rebooted both rpi and tradfri gateway...

**Comment by mo8Zomo0** [comment]
My main intention is to have the proper state synced as I use the ikea light switches. 
So not happy that observations would be off if I upgrade. 
Maybe have a configurable limit, like poll every 30 sec or minute till a good coap 
publish/subscribe is present.

**Comment by moroen** [comment]
Good idea, and implemented in the latest commit just pushed. Default interval set to 30 seconds. Hopefully this will increment the time between gateway resets...

pytradfri just implemented an api for restarting the gateway, might be an idea to implement an option for automatic restart at a user specified time, if the gateway continues to freeze after a certain time...

**Comment by mo8Zomo0** [comment]
have not tried it yet and also did not check ,but I could picture also the interval in between the different devices can play a role. At least when I tried my own script, especially I could hang it up by just sending a hand full of commands to groups, but I guess also lamps might react fragile at some point
