### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by raf6410** [moroen/IKEA-Tradfri-plugin#18]
Hi,

I very happy to this plugins, i works well in my home but now i newt o restart TRADFRI gateway every day.

After some hours, the plugins can't connect to the gateway (see log  below).
When i see this un domoticz log, I need to restert TRADFRI gateway because the gateway refuse all connection ( tablet, smartphone, raspberry PI .

> 2017-10-10 18:36:35.074 (Ikea) Initialized version 1.0.3, author 'moroen'
> 2017-10-10 18:36:35.129 PluginSystem: Starting I/O service thread.
> 2017-10-10 18:36:35.179 (Ikea) Connected successfully to: 192.168.1.32
> 2017-10-10 18:36:46.249 (Ikea) Received: b'{"action": "clientConnect", "status": "Ok", "version": "0.4"}'
> 2017-10-10 18:36:46.249 (Ikea) Received: b'{"action": "setConfig", "status": "Failed", "error": "Connection timed out"}'
> 2017-10-10 18:36:46.249 (Ikea) Command setConfig failed with error: Connection timed out.
> 2017-10-10 18:36:46.249 (Ikea) {'action': 'setConfig', 'status': 'Failed', 'error': 'Connection timed out'}

I never see that before i install your plugins.

Could you help me?

RAF

**Comment by moroen** [comment]
For now, the best option is to disable observations, as it appears to freeze the gateway after some time. Working on a better way for observing changes, but progress is slow...
