### ISSUE TITLE
pytradfri 4.0

### ISSUE THREAD

**Issue by magnusheino** [moroen/IKEA-Tradfri-plugin#24]
Please add support for pytradfri 4.0

I am trying to get it working, but my python skills are too rusty :-(

https://github.com/ggravlingen/pytradfri/pull/92/files
https://github.com/home-assistant/home-assistant/issues/10252

**Comment by moroen** [comment]
I'm on it! :)

**Comment by moroen** [comment]
The lattest commit supports the new IDENT/PSK credentials of the gateway and supports / requires pytradfri version 4.0.2 or later.
