### ISSUE TITLE
Segfault using master

### ISSUE THREAD

**Issue by magnusheino** [moroen/IKEA-Tradfri-plugin#25]
> 2017-11-06 21:11:10.102  (Tradfri) Received: b'{"action": "deviceUpdate", "status": "Ok", "result": [{"DeviceID": 65555, "Name": "Spot3", "State": true, "Level": 235, "Hex": "f1e0b5"}]}'
> 2017-11-06 21:11:10.103  (Tradfri - Spot3) Updating device from 1:'94' to have values 1:'94'.
> 2017-11-06 21:11:10.106  (Tradfri) Hex: f1e0b5 Target Unit: 2 Target level: 20
> 2017-11-06 21:11:10.106  (Tradfri - Spot3 - WB) Updating device from 1:'20' to have values 1:'20'.
> 2017-11-06 21:11:10.109  (Tradfri) Received 138 bytes of data:.
> 2017-11-06 21:11:10.109  (Tradfri)     7b 22 61 63 74 69 6f 6e 22 3a 20 22 64 65 76 69 63 65 55 70     {"action":."deviceUp
> 2017-11-06 21:11:10.109  (Tradfri)     64 61 74 65 22 2c 20 22 73 74 61 74 75 73 22 3a 20 22 4f 6b     date",."status":."Ok
> 2017-11-06 21:11:10.109  (Tradfri)     22 2c 20 22 72 65 73 75 6c 74 22 3a 20 5b 7b 22 44 65 76 69     ",."result":.[{"Devi
> 2017-11-06 21:11:10.110  (Tradfri)     63 65 49 44 22 3a 20 36 35 35 34 38 2c 20 22 4e 61 6d 65 22     ceID":.65548,."Name"
> 2017-11-06 21:11:10.110  (Tradfri)     3a 20 22 53 70 6f 74 34 22 2c 20 22 53 74 61 74 65 22 3a 20     :."Spot4",."State":.
> 2017-11-06 21:11:10.110  (Tradfri)     74 72 75 65 2c 20 22 4c 65 76 65 6c 22 3a 20 31 33 33 2c 20     true,."Level":.133,.
> 2017-11-06 21:11:10.110  (Tradfri)     22 48 65 78 22 3a 20 22 65 66 64 32 37 35 22 7d 5d 7d .. ..     "Hex":."efd275"}]}
> 2017-11-06 21:11:10.110  (Tradfri) Calling message handler 'onMessage'.
> 2017-11-06 21:11:10.110  (Tradfri) Received: b'{"action": "deviceUpdate", "status": "Ok", "result": [{"DeviceID": 65548, "Name": "Spot4", "State": true, "Level": 133, "Hex": "efd275"}]}'
> 2017-11-06 21:11:10.111  (Tradfri - Spot4) Updating device from 1:'53' to have values 1:'53'.
> 2017-11-06 21:11:10.114  (Tradfri) Hex: efd275 Target Unit: 4 Target level: 30
> 2017-11-06 21:11:10.114  (Tradfri - Spot4 - WB) Updating device from 1:'30' to have values 1:'30'.
> 2017-11-06 21:11:10.116  (Tradfri) Received 137 bytes of data:.
> 2017-11-06 21:11:10.117  (Tradfri)     7b 22 61 63 74 69 6f 6e 22 3a 20 22 64 65 76 69 63 65 55 70     {"action":."deviceUp
> 2017-11-06 21:11:10.117  (Tradfri)     64 61 74 65 22 2c 20 22 73 74 61 74 75 73 22 3a 20 22 4f 6b     date",."status":."Ok
> 2017-11-06 21:11:10.117  (Tradfri)     22 2c 20 22 72 65 73 75 6c 74 22 3a 20 5b 7b 22 44 65 76 69     ",."result":.[{"Devi
> 2017-11-06 21:11:10.117  (Tradfri)     63 65 49 44 22 3a 20 36 35 35 35 39 2c 20 22 4e 61 6d 65 22     ceID":.65559,."Name"
> 2017-11-06 21:11:10.117  (Tradfri)     3a 20 22 54 61 6b 31 22 2c 20 22 53 74 61 74 65 22 3a 20 66     :."Tak1",."State":.f
> 2017-11-06 21:11:10.117  (Tradfri)     61 6c 73 65 2c 20 22 4c 65 76 65 6c 22 3a 20 36 39 2c 20 22     alse,."Level":.69,."
> 2017-11-06 21:11:10.117  (Tradfri)     48 65 78 22 3a 20 22 65 37 38 38 33 34 22 7d 5d 7d .. .. ..     Hex":."e78834"}]}
> 2017-11-06 21:11:10.118  (Tradfri) Calling message handler 'onMessage'.
> 2017-11-06 21:11:10.118  (Tradfri) Received: b'{"action": "deviceUpdate", "status": "Ok", "result": [{"DeviceID": 65559, "Name": "Tak1", "State": false, "Level": 69, "Hex": "e78834"}]}'
> 2017-11-06 21:11:10.118  (Tradfri - Tak1) Updating device from 0:'27' to have values 0:'27'.
> 2017-11-06 21:11:10.121  Error: (Tradfri) 'onMessage' failed 'KeyError'.
> Segmentation fault

Any  idea whats causing the segfault?

**Comment by magnusheino** [comment]
> Nov 06 21:12:47 xx twistd[19351]: --- <exception caught here> ---
> Nov 06 21:12:47 xx twistd[19351]: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
> Nov 06 21:12:47 xx twistd[19351]: result = f(*args, **kw)
> Nov 06 21:12:47 xx twistd[19351]: File "/home/domoticz/domoticz/plugins/IKEA-Tradfri/tradfri.tac", line 247, in announce
> Nov 06 21:12:47 xx twistd[19351]: print("Error in annouce: {0}:{1}".format(e, e.message))
> Nov 06 21:12:47 xx twistd[19351]: builtins.AttributeError: 'RequestTimeout' object has no attribute 'message'
>

**Comment by magnusheino** [comment]
> Nov 06 21:29:20 xx twistd[20355]: File "/usr/local/lib/python3.6/site-packages/pytradfri/api/libcoap_api.py", line 98, in request
> Nov 06 21:29:20 xx twistd[20355]: result = self._execute(api_command)
> Nov 06 21:29:20 xx twistd[20355]: File "/usr/local/lib/python3.6/site-packages/pytradfri/api/libcoap_api.py", line 82, in _execute
> Nov 06 21:29:20 xx twistd[20355]: raise RequestTimeout() from None
> Nov 06 21:29:20 xx twistd[20355]: pytradfri.error.RequestTimeout:
> Nov 06 21:29:20 xx twistd[20355]: 2017-11-06T21:29:19+0100 [stdout#info] Disconnected
>

**Comment by moroen** [comment]
Not quite sure, but a few things to try:
1. Install newest version of pytradfri and plugin
2. Delete the IKEA-plugin from the hardware-page and try to add it and all devices again.

**Comment by magnusheino** [comment]
Plugin commits on November 7 solved the problem. Now its working :-)
