### ISSUE TITLE
Domoticz can not start if adapter is running

### ISSUE THREAD

**Issue by Cyberwizzard** [moroen/IKEA-Tradfri-plugin#26]
I have the odd situation that Domoticz 3.0.8.8153-7 on my Synology crashes for some reason. The adapter is running in a Docker on the Synology NAS as well.

If I first start Domoticz and then the Docker container, all is well.

However if I start Domoticz and the container was still running, Domoticz seems to crash when loading the plugins. Killing the container, starting Domoticz and then starting the container again allows me to start Domoticz.

I am not sure why this is happening and I am trying to get logs which show what is going on but I am reporting it in case I am not the only one who has this issue.

**Comment by moroen** [comment]
New version do not longer use the adapter. Closing issue.
