### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by magnusheino** [moroen/IKEA-Tradfri-plugin#28]
`2017-11-10 17:35:01.093  Error: (Tradfri) 'onMessage' failed 'UnboundLocalError':'local variable 'targetLevel' referenced before assignment'.`

**Comment by moroen** [comment]
Can you provide some more context? I'm unable to reproduce this error, and by looking at the code, I fail to see where targetLevel is referenced without assignment...

**Comment by moroen** [comment]
Fixed... :)
