### ISSUE TITLE
[Feature Request]: Get status from switch without being paired to bulb

### ISSUE THREAD

**Issue by coolnovember** [moroen/IKEA-Tradfri-plugin#35]
This is a feature request. The wireless remote control makes a for a very nice wall switch. Is there any way to get the commands sent to the switch as a domoticz event? I could see myself buying a couple of these and using them as wireless switches to interact with Domoticz.

**Comment by moroen** [comment]
As far as I know, there is no way to observe remotes (and motion sensors etc) using the COAP interface to the gateway, so at the moment, that's not possible.
