### ISSUE TITLE
Docker: ImportError: cannot import name 'APIFactory'

### ISSUE THREAD

**Issue by droskam** [moroen/IKEA-Tradfri-plugin#36]
While following the docker guide (step 7), running "python tradfri.tac" results in:

Traceback (most recent call last):
  File "tradfri.tac", line 14, in <module>
    from pytradfri.api.libcoap_api import APIFactory
ImportError: cannot import name 'APIFactory'

Same results while using:
create.sh && start.sh

**Comment by moroen** [comment]
Sorry for the late reply. The docker script needs to be updated to the latest version of pytadrfri. I'll try to get around to it, but at the moment the time I have to spend on this is limited.

**Comment by moroen** [comment]
Dockerfiles updated and should work again.
