### ISSUE TITLE
compile the golang version on a RPI with Raspbian 8

### ISSUE THREAD

**Issue by mo8Zomo0** [moroen/IKEA-Tradfri-plugin#37]
compile fails with:

```
# make
cd src/tradfri; go get -v; go install -v
../github.com/moroen/go-tradfricoap/coap.go:9:2: /root/src/tradfri/src/github.com/moroen/canopus/dtls.go: malformed #cgo argument: -L/usr/local/opt/openssl@1.1/lib
../github.com/moroen/go-tradfricoap/coap.go:9:2: /root/src/tradfri/src/github.com/moroen/canopus/dtls.go: malformed #cgo argument: -L/usr/local/opt/openssl@1.1/lib
Makefile:16: recipe for target 'bin/tradfri' failed
make: *** [bin/tradfri] Error 1
```

_# head -n5 /root/src/tradfri/src/github.com/moroen/canopus/dtls.go_
```
package canopus

/*
#cgo LDFLAGS: -L/usr/local/opt/openssl@1.1/lib -L${SRCDIR}/openssl  -lssl -lcrypto -ldl
#cgo CFLAGS: -g -Wno-deprecated -Wno-error -I/usr/local/opt/openssl@1.1/include -I${SRCDIR}/openssl/include  -Wno-incompatible-pointer-types -Wno-return-type
```

Btw, there is 4 branches, are the aiocoap or golang to be used or better the default one?
Just upgraded domoticz to beta and at least the old plugin was not working anymore, 
so I was looking at the code again. Still my min intention is to also show the status change
back of an ikea lamp to domoticz.

**Comment by moroen** [comment]
I would recommend the python version, master or development-branch. The aiocoap version is a dead end (at least for now) and the golang version not ready for general use... I've been to busy elsewhere to do any real development for a while, but plan to return to this project in the near future.
