### ISSUE TITLE
Removing Identities

### ISSUE THREAD

**Issue by Reneke43** [moroen/IKEA-Tradfri-plugin#41]
When generating a PSK using:

_coap-client -m post -u "Client_identity" -k "GATEWAY-KEY" -e '{"9090":"IDENT"}' "coaps://IP:5684/15011/9063"_

The IDENT is written to the GATEWAY I presume. Is there a way to list all IDENT's and remove them from the GATEWAY?
Because, when I try to get a PSK using a previously used IDENT, all I get as output is something like:

_v:1 t:CON c:POST i:fe22 {} [ ]
4.00_

**Comment by moroen** [comment]
The error you get is consistent with trying to generate a PSK for an already used IDENT.

As far as I know, there is no way to list all idents and no way to generate a new PSK for an already used ident...
