### ISSUE TITLE
HasWB/HasRGB/State boolean/string issue

### ISSUE THREAD

**Issue by ehoutsma** [moroen/IKEA-Tradfri-plugin#43]
In Domoticz v4.9919 the aDev["State"] isn't returned as a boolean but as a string, causing the light not being turned on in Domoticz. 

The same goes for aLight["HasWB"] and aLight["HasRGB"], the currect code turns every WB light to turn up as an RGB right.

My solutions:
In registerDevices:
```
            devID = str(aLight['DeviceID'])
            ikeaIds.append(devID)

+            if aLight["HasRGB"] == "true":
+               aLight["HasRGB"] = True
+
+            if aLight["HasWB"] == "true":
+                aLight["HasWB"] = True

```

and in updateDeviceState
```
            if aDev["State"] == True:
                nVal = 1
+            elif aDev["State"] == "true":
+                nVal = 1
+            elif aDev["State"] == "false":
+                nVal = 0
+            elif aDev["State"] == False:
-            if aDev["State"] == False:
                nVal = 0

```

**Comment by moroen** [comment]
Thanks for bringing this to my attention!

The latest commit to the development-branch should fix this issue.
