### ISSUE TITLE
Time-out to Tradfri hub causes update to Domoticz to stop

### ISSUE THREAD

**Issue by basrieter** [moroen/IKEA-Tradfri-plugin#56]
Apparently there is a timeout somewhere the try-except generates a new exception because the RequestTimeout does not have an attribute `message`:

```
,2018-10-31T08:12:15.474642160Z Unhandled error in Deferred:
,2018-10-31T08:12:15.487248324Z 
,2018-10-31T08:12:15.487415875Z Traceback (most recent call last):
,2018-10-31T08:12:15.487486395Z   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/base.py", line 1267, in run
,2018-10-31T08:12:15.487557384Z     self.mainLoop()
,2018-10-31T08:12:15.487622853Z   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/base.py", line 1276, in mainLoop
,2018-10-31T08:12:15.487693008Z     self.runUntilCurrent()
,2018-10-31T08:12:15.487757904Z   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/base.py", line 902, in runUntilCurrent
,2018-10-31T08:12:15.487827955Z     call.func(*call.args, **call.kw)
,2018-10-31T08:12:15.487894257Z   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/task.py", line 239, in __call__
,2018-10-31T08:12:15.487962538Z     d = defer.maybeDeferred(self.f, *self.a, **self.kw)
,2018-10-31T08:12:15.488028266Z --- <exception caught here> ---
,2018-10-31T08:12:15.488095506Z   File "/usr/local/lib/python3.5/dist-packages/twisted/internet/defer.py", line 151, in maybeDeferred
,2018-10-31T08:12:15.488165036Z     result = f(*args, **kw)
,2018-10-31T08:12:15.488229359Z   File "tradfri.tac", line 337, in announce
,2018-10-31T08:12:15.488356389Z     print("Error in annouce: {0}:{1}".format(e, e.message))
,2018-10-31T08:12:15.488424670Z builtins.AttributeError: 'RequestTimeout' object has no attribute 'message'
```

This basically stops the tradfri.tac from sending updates to Domoticz. I can still switch devices from Domoticz, but switching them with the Ikea remotes, is not show in Domoticz

**Comment by moroen** [comment]
This is due to how twisted handles errors in deferred routines.  

Stable observations without the need for polling are a priority, but since that's still difficult, I'll try to make the polling a bit more stable. Thanks for reminding me of this issue, I'll move it up on my "priority list"... :)

Regards,
M

**Comment by basrieter** [comment]
Sure, np. But the AttributeError in the `except`, is that something we can fix? Perhaps with a more specific exception:

````
except RequestTimeout, e:
    print("Error in annouce: {0}:{1}".format(e, e.<someattributethatworks>))
    pass

except Exception as e: 
    print("Error in annouce: {0}:{1}".format(e, e.message))
````

**Comment by moroen** [comment]
Probably, but handling exceptions in twisted deferred functions are (at least I found it to be) a nightmare.

I have pushed a simpler solution to the development branch. This is a solution more in line with future planed changes (which is to get rid of coap-client and twisted and replace them with aiocoap).

If you would be as kind as to try the development-branch?

Regards,
M

**Comment by basrieter** [comment]
Updated both the plugin as the connector to development. Got some errors every now and then:

```
2018-11-04 19:48:00.303 Error: (Tradfri) No transport, write directive to 'Main' ignored.
```

And if I use Domoticz to switch off/on, the actual switch does not change on the screen. It is only updated after the polling interval, which I have set it to 10 seconds.

**Comment by moroen** [comment]
The error with status not being updated right away should  be fixed in the latest commit to development.

The No-transport error needs further investigation.

**Comment by basrieter** [comment]
Using the development version for 2 days now. So far so good. The problem usually surfaced after a longer periode, so let's keep our fingers crossed.

**Comment by moroen** [comment]
Thank you for the feedback. I'll keep this issue open for a couple of more days, and if no reports of any errors, merge into the master branch!

**Comment by moroen** [comment]
No further errors reported. Merged into master

**Comment by basrieter** [comment]
You beat me to it. No problems so far. Thanks for the fix.

**Comment by moroen** [comment]
:)

**Comment by basrieter** [comment]
After some weeks I still encounter connection losses to the hub. I need to restart it to make it all work again.

It seems like after some time the it just won't accept any more connections. I have the idea that it comes back faster if I set the polling interval to lower values (faster polling)

**Comment by martialman** [comment]
Hello, I'm sorry, i have the same problem than basrieter, with  the same Tradfri controller output and the same error in domoticz, what advise me to help me? I am french, I could misunderstand because of the translations, the devellopement is the beta version of domoticz ??
My domoticz version : 4.10256 beta on raspberry.

I thank you in advance

**Comment by moroen** [comment]
You should use the master version regardless of domoticz stable or beta, the plugin is unified for both versions. Could you please post the log describing the error?

**Comment by martialman** [comment]
Tank you for your help,
I'm sorry, but now i have new problem, i think it's the upgrade?
my log : 
/usr/local/lib/python3.4/dist-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
IKEA-tradfri COAP-adaptor version 0.8.3 started (command line)!

In first time my error log is similar to basrieter.

Tank you

**Comment by moroen** [comment]
Your python version is too old, you need to use at least version 3.5, but 3.6 is recommended!

**Comment by martialman** [comment]
I'm sorry but wanting to upgrade libtool my raspberry planted by asking me for a login at startup after hours of testing for the repaired I ended up all reinstall and everything works now very very well thank you very much for your quick answers soon thank you
