### ISSUE TITLE
Executable path is not absolute, ignoring: None --nodaemon

### ISSUE THREAD

**Issue by perkovich** [moroen/IKEA-Tradfri-plugin#60]
When starting "sudo systemctl start ikea-tradfri.service" I got this error:

Nov 27 22:03:00 domoticz systemd[1]: [/etc/systemd/system/ikea-tradfri.service:6] Executable path is not absolute, ignoring: None --nodaemon        --ru
Nov 27 22:03:00 domoticz systemd[1]: ikea-tradfri.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.

I don't know how it works but just to try something I added twistd to the ExecStart:

ExecStart=/usr/local/bin/twistd --nodaemon \

and then it started up just fine. I kept it because it worked but I am not sure why it doesn't work without it. I can't get it to work with "None".

**Comment by moroen** [comment]
If you try to run ./configure.py --skip-config --create-service again, and post the output and resulting ikea-tradfri.service file?

**Comment by mvl-nl** [comment]
Just wanted to let you know I have the same problem.
I use a newly installed Raspbian-lite. I generated the ikea-tradfri.service as specified under user 'pi'.
The content is:

[Unit]
Description=IKEA Tradfri COAP-adapter

[Service]
Type=simple
ExecStart=None --nodaemon \
      --rundir=/home/pi/domoticz/plugins/IKEA-Tradfri \
      --pidfile=/home/pi/domoticz/plugins/IKEA-Tradfri/twistd.pid \
      --python=/home/pi/domoticz/plugins/IKEA-Tradfri/tradfri.tac

User=pi
Group=pi

Restart=always

**Comment by moroen** [comment]
configure.py doesn't seem to find the twistd binary, what does
`$ which twistd`
return?

**Comment by mvl-nl** [comment]
'which' does not find it.
When I do a 'find' starting from '/' it is found is in 
/home/pi/.local/bin/twistd

Should twisted installation be run with sudo?
Or add the .local/bin to the PATH?

**Comment by mvl-nl** [comment]
Ok: doing 'sudo pip3 install twisted' and then regenerating the service file solves it.

# sudo systemctl status ikea-tradfri.service
● ikea-tradfri.service - IKEA Tradfri COAP-adapter
   Loaded: loaded (/lib/systemd/system/ikea-tradfri.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-12-04 13:42:46 CET; 7s ago

**Comment by perkovich** [comment]
$ which twistd
/usr/local/bin/twistd

and

pi@domoticz:~ $ sudo pip3 install twisted
Requirement already satisfied: twisted in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: PyHamcrest>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from twisted)
Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python3.5/dist-packages (from twisted)
Requirement already satisfied: zope.interface>=4.4.2 in /usr/local/lib/python3.5/dist-packages (from twisted)
Requirement already satisfied: incremental>=16.10.1 in /usr/local/lib/python3.5/dist-packages (from twisted)
Requirement already satisfied: hyperlink>=17.1.1 in /usr/local/lib/python3.5/dist-packages (from twisted)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.5/dist-packages (from twisted)
Requirement already satisfied: Automat>=0.3.0 in /usr/local/lib/python3.5/dist-packages (from twisted)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from PyHamcrest>=1.9.0->twisted)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from PyHamcrest>=1.9.0->twisted)
Requirement already satisfied: idna>=2.5 in /usr/local/lib/python3.5/dist-packages (from hyperlink>=17.1.1->twisted)

**Comment by moroen** [comment]
With the latest commit, configure.py displays an error message when twistd isn't found.

Thanks for the report!
