### ISSUE TITLE
Battery levels

### ISSUE THREAD

**Issue by basrieter** [moroen/IKEA-Tradfri-plugin#64]
Would it be possible to show the battery level of switches that are connected to the lights?

**Comment by basrieter** [comment]
I see you are working on the battery levels? Is 5eddbe5 the only thing that is required or do is it not yet stable?

**Comment by basrieter** [comment]
Great! Let me know if you need some testing at some point. Easy to spin up a new Docker container here. But no hurry! I know the pressure of working on open source projects. Don't forget to spend time on other (personal) things too!

**Comment by moroen** [comment]
Intitial support for monitoring battery-levels has been added. It's rather crude at the moment, using the default percentage-type, but I guess it can be made more "elegant" somewhere along the road. 

Battery-status is updated on domoticz startup, and once every 60 minutes. This interval is hard-coded, due to limitations in the plugin framework,

Please test the development branch and bring feedback!

**Comment by basrieter** [comment]
Running it as we speak. Will let you know how it goes.

**Comment by basrieter** [comment]
I checked the battery levels for the past 5 days, but they don't seem to change at all. One battery is still at 100% while I have to replace it, because it has a low voltage. So something seems odd here.

**Comment by moroen** [comment]
Hm, strange... Does the updated time on the domoticz controlls change once an hour?

**Comment by basrieter** [comment]
Really, those are the same values I have: 

![image](https://user-images.githubusercontent.com/1310443/52299501-d6a46d00-2985-11e9-8987-7ccc9fb4d009.png)

**Comment by moroen** [comment]
I've checked the raw data from the gateway, and the values reported via pytradfri looks to be correct, so the problem probably lies with the gateway... Keeping this issue open for now, pending further research.

**Comment by basrieter** [comment]
Ok. Seems that Home Assistant does have it working. Perhaps there is an option to peek there?

**Comment by moroen** [comment]
Ok, so HA on your system reports a correct battery status?

**Comment by basrieter** [comment]
No, I did not try that. Just read in their forums. I am a 100% Domoticz person.

**Comment by moroen** [comment]
I've been running an instance of HA for a couple of days, the battery levels are the same in HA as in Domoticz, and haven't changed a bit, still 74, 100 and 100 for my three remotes. So my initial conclusion is that the gateway somehow doesn't report the battery status correctly. This MIGHT be a problem with pytradfri, which is the basis for tradfri-support in both my plugin and HA.

Keeping the issue open pending further observations.

**Comment by wvdweerd** [comment]
Any updates on this? Are you still trying to get this working?

I have had already two remotes where the battery was completely empty before I noticed. Then I had to remove and register the remote and lights again in the Ikea hub. And they then appear as new  lights in Domoticz, so I had to add the timers again and add them to the dashboard...

Very annoying, so I would be great to get battery level updates in Domoticz :-)

**Comment by moroen** [comment]
Support for monitoring battery levels have been added to latest version!

**Comment by basrieter** [comment]
Nice! Will give it a try asap

**Comment by basrieter** [comment]
Working like a charm!
