### ISSUE TITLE
Support tot ikea curtains

### ISSUE THREAD

**Issue by robgardien** [moroen/IKEA-Tradfri-plugin#65]
Will there be support for the Ikea tradfri curtains from the plugin?

**Comment by axel2906** [comment]
Hi, is there more update for the curtains ?

**Comment by moroen** [comment]
Due to numerous delays, the Tradfri curtains have been unavailable i Norway until now. I've just checked the IKEA website, and the curtains appear to be available, so as soon as I can get a couple of them delivered, I'll start implementing support for them in Domoticz!

**Comment by axel2906** [comment]
great !!! 
i've bought one (in Belgium) and i've tried to see the integration of the blinds. I can see the blind wiht homebridge so maybe can this help you

![tradfri£_gateway_blinds](https://user-images.githubusercontent.com/55280764/64877821-6fa11200-d652-11e9-9e1a-141a6c29975c.JPG)

**Comment by axel2906** [comment]
Hi,

is it more news about support of the curtains in domoticz ?

**Comment by moroen** [comment]
Better late than never, the last version of the plugin (version 0.7.0 at the moment of writing) supports the tradfri curtains!

**Comment by axel2906** [comment]
You are the boss ! I will try it today
