### ISSUE TITLE
adapter_start.sh not working

### ISSUE THREAD

**Issue by robgardien** [moroen/IKEA-Tradfri-plugin#68]
Please edit the adapter_start.sh to reflect the new configure.py

#!/usr/bin/env bash

if [ ! -f /usr/src/app/config.json ]; then
    /usr/src/app/configure.py **config** "$GW_IP""$GW_PSK"
fi
python3 tradfri.tac

**Comment by moroen** [comment]
Didn't think of that... Fixed! Thanks!
