### ISSUE TITLE
Error: Unknown error when launching configure.py

### ISSUE THREAD

**Issue by yabolek** [moroen/IKEA-Tradfri-plugin#74]
Hello,

When I launch ./configure.py to add my GW it fails with "Error: Unknown error". Double checked both the IP and KEY. Looked at the script, but cannot see nothing useful. Any help would be appreciated.

Thanks!

**Comment by moroen** [comment]
Try:

./configure.py --debug IP KEY 

and post the output here, and I'll look at it!

Regards,
M

**Comment by yabolek** [comment]
Hi! Thanks for a quick reply.. I somehow missed the debug option - libcoap was the problem. I re-launched the coap install script and now it works fine :) Thanks again, really appreciated :)

**Comment by moroen** [comment]
Glad it worked out!
