### ISSUE TITLE
handling of white colour temperature.

### ISSUE THREAD

**Issue by mo8Zomo0** [moroen/IKEA-Tradfri-plugin#8]
some comments about colour temperature:

* the secondary device has 3 levels 0=cold, 10=normal, 20=warm.
It might be more handy to have 0=off and then 10 cold, 20 normal 30 warm
Currently when clicking on the bulb icon of the switch the WB changes to cold, where I think off would be nicer or it could be selected to be hidden.
* lamps which only support 2700 show also up with a selector for warm/cold
* I am still not sure if I like or dislike the secondary device, but I see this is more a limitation of domoticz, some WW and RGBWW switch/dimmer would be needed where you can switch, dim and select the kind of white colour temperature
* ikea seems to start rolling out RGB LEDs, just that you know and your mentally prepared.
   I have not found out much, but some discussion is here https://bitsex.net/software/2017/coap-endpoints-on-ikea-tradfri/#comment-43652 
  the order code for the kit is: 703.389.51 but does not even seem to be listed on the IKEA site.

**Comment by moroen** [comment]
To be honest, I don't like the secondary device for WB, but as far as I can tell, domoticz doesn't have a type that supports both white balance and dimming, in fact I suspect it might be easier to implement the RGB light when it arrives. Changing the level of the secondary device as you mention,  so that the bulb is on/off is a good idea!

**Comment by leejoow** [comment]
For a Daikin plugin I'm developing I'm using selector switches with a hidden off level and change the nvalue to make the icon gray. Works quite nicely.

https://github.com/leejoow/domoticz_daikin_BRP069A42

**Comment by deennoo** [comment]
Will test on my side, but does python lib doesn't show bulb type/commercial name/Power i have 1 of each bulb to test it this evening.

Btw thanks for your plugin, be aware that Ikea promise an api for this automne.

**Comment by moroen** [comment]
WB fixed, still need to figure out some way of checking bulb properties.
