### ISSUE TITLE
Domoticz Error Log messages

### ISSUE THREAD

**Issue by mpovel** [moroen/IKEA-Tradfri-plugin#85]
Hello,
I really love to add all my Smart Home stuff to domoticz. So I am trying to get the Tradfri stuff also controlled, and it works at least. But I get several error messages like:
2019-12-02 12:39:47.378  Error: (Tradfri) 'onMessage' failed 'KeyError'.
2019-12-02 12:39:47.378  Error: (Tradfri) ----> Line 569 in '/home/pi/domoticz/plugins/Tradfri/plugin.py'
2019-12-02 12:39:47.378  Error: (Tradfri) ----> Line 371 in '/home/pi/domoticz/plugins/Tradfri/plugin.py'
2019-12-02 12:39:47.378  Error: (Tradfri) ----> Line 224 in '/home/pi/domoticz/plugins/Tradfri/plugin.py'

And I can't make any sense of them. I can control devices OK with domoticz and also with the cli.

Thanks

Michael

**Comment by SchietSchijf** [comment]
Did you use the correct code? it's the one from underneath the qr code.

**Comment by mpovel** [comment]
Hi Roeland,

I am using the code from underneath. I even can control my devices, but I still get the error messages in the logfile.

 

Cu

Michael

 

Von: Roeland van den Broeck [mailto:notifications@github.com] 
Gesendet: Montag, 2. Dezember 2019 14:18
An: moroen/IKEA-Tradfri-plugin <IKEA-Tradfri-plugin@noreply.github.com>
Cc: mpovel <Michael@Povel-Walsrode.de>; Author <author@noreply.github.com>
Betreff: Re: [moroen/IKEA-Tradfri-plugin] Domoticz Error Log messages (#85)

 

Did you use the correct code? it's the one from underneath the qr code.

**Comment by moroen** [comment]
I would recommend that you try the "new" version, found in the pycoap branch, please check the readme in that branch for instructions!
