### ISSUE TITLE
Python Ikea) 'onMessage' failed 'TypeError':'onMessage() missing 2 required positional arguments: 'Status' and 'Extra''.

### ISSUE THREAD

**Issue by deennoo** [moroen/IKEA-Tradfri-plugin#9]
Just testing your plugin

- Debian Jessie on x86-64b VM
- Domoticz 3.8330
- Your plugin version master branch 15 days old update

Ikea bridge + round remote + 'TRADFRI bulb E27 WS opal 980lm warm / cold white',

running COAP-adaptor on test : python3 tradfri.tac

Can see the on ssh windows all the log, works great and fast !

`{'action': 'deviceUpdate', 'status': 'Ok', 'result': [{'Hex': 'f1e0b5', 'DeviceID': 65537, 'Name': 'TRADFRI bulb E27 WS opal 980lm', 'State': True, 'Level': 254}]}`

Maybe hex can be a way to looks which bulb can be white dimmable and not, or just first commercial name (keep out of the box name unitle add to domoticz, get hex and device id, and then do what you want)

on domoticz no device created, and facing this error on log : 

(Python Ikea<<---name of your plugin on my test machine) 'onMessage' failed 'TypeError':'onMessage() missing 2 required positional arguments: 'Status' and 'Extra''.

Of course no bulb is created on domoticz

How to solve this please ?

**Comment by moroen** [comment]
You have to match the branch of the plugin to the version of domoticz your using. The master branch of this plugin should work with the latest stable/master branch of domoticz, the development branch should work with domoticz/development (or rather python-enabled) branch of domoticz.

As to lights being dimmable or not, or able to change WB, it's possible to get the model description of the different bulbs, and maintain some kind of list of the different features of the bulbs. I haven't gotten so far, but it's on the "to-do" list

**Comment by deennoo** [comment]
OK done and working with dev branche, thx for your help and job !

**Comment by moroen** [comment]
Glad it worked out!
