### ISSUE TITLE
Domoticz stops working with new "master" version

### ISSUE THREAD

**Issue by basrieter** [moroen/IKEA-Tradfri-plugin#91]
Every since I upgraded to the new "master" branche version (without the additional service) my Domoticz stops responding after about 24-36 hours.

Is there any way I can provide you with logging regarding this issue?

**Comment by moroen** [comment]
Domoticz as a whole or just tradfri?

**Comment by basrieter** [comment]
Domoticz as a whole. I initially noticed this because I could not access Domoticz via the brower. I was still able to access the Raspberry Pi via SSH and noticed the Domoticz process stopped. I had to restart Domoticz.

I reverted back to 0ce7c2741123025c291dc6517256d88c8c801c24 which was the version I was using for a while now. The Tradfri service is running on a Docker image in my Docker swarm. Then Domoticz runs for weeks.

**Comment by moroen** [comment]
Is there anything in the logs, up to the moment where domoticz just dies? Which version of domoticz are you using? Do you have some kind of memory log, to see if memory usage spikes or gradually increases?

**Comment by basrieter** [comment]
I use Domoticz v4.10717 (May 9th 2019). The problem is that the in-app log gets cleared whenever I start Domoticz.

I can go back the latest master of the Tradfri plugin and start Domoticz with a file log tonight.

**Comment by moroen** [comment]
I think I have found your problem, the lastest version (0.7.0) should hopefully fix this. Just make sure that you also upgrade to the latest version of pycoap (0.7.0) as well! If not, let domoticz run from the command line, then you'll get the full log and some notion of what's happening when domoticz dies...

I'm closing this issue, please feel free to reopen if the latest version still fails!

**Comment by basrieter** [comment]
Just upgraded and I will see what happens. I will update you after some days.

**Comment by basrieter** [comment]
@moroen It has been running ever since I upgraded to 0.7.0 of both the plugin as pycoap. Super!

**Comment by moroen** [comment]
Great!
