### ISSUE TITLE
Cannot start ikea-Trådfri.service

### ISSUE THREAD

**Issue by EvertJob** [moroen/IKEA-Tradfri-plugin#93]
Hi,

I'm having trouble with starting the service from the plugin.
When starting the plugin true systemctl i's failed because the COAP Adapter cannot start, see code below:
```pi@raspberrypi:~ $ /bin/systemctl status ikea-tradfri.service
 ikea-tradfri.service - IKEA Tradfri COAP-adapter
   Loaded: loaded (/etc/systemd/system/ikea-tradfri.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-01-11 10:06:31 CET; 6s ago
  Process: 25008 ExecStart=/usr/local/bin/twistd --nodaemon --rundir=/home/pi/domoticz/plugins/IKEA-Tradfri --pidfile=/home/pi/domoticz/plugins/IKEA-Tradfri/twistd.pid --python=/home/pi/domoticz/plugins/I
 Main PID: 25008 (code=exited, status=1/FAILURE)

jan 11 10:06:30 raspberrypi systemd[1]: ikea-tradfri.service: Failed with result 'exit-code'.
jan 11 10:06:31 raspberrypi systemd[1]: ikea-tradfri.service: Service hold-off time over, scheduling restart.
jan 11 10:06:31 raspberrypi systemd[1]: Stopped IKEA Tradfri COAP-adapter.
jan 11 10:06:31 raspberrypi systemd[1]: ikea-tradfri.service: Start request repeated too quickly.
jan 11 10:06:31 raspberrypi systemd[1]: Failed to start IKEA Tradfri COAP-adapter.
jan 11 10:06:31 raspberrypi systemd[1]: ikea-tradfri.service: Unit entered failed state.
jan 11 10:06:31 raspberrypi systemd[1]: ikea-tradfri.service: Failed with result 'exit-code'.
```

When I try to start using the  `adapter_start.py` or the `python3 tradfri.tac` everything works fine, but not on a reboot or when closing the script.

Does anyone has any suggestion to fix the ```ikea-tradfri.service``` so it will load and start after a reboot?

The content of my `ikea-tradfri.service` is as below:
```[Unit]
Description=IKEA Tradfri COAP-adapter

[Service]
Type=simple
ExecStart=/usr/local/bin/twistd --nodaemon \
      --rundir=/home/pi/domoticz/plugins/IKEA-Tradfri \
      --pidfile=/home/pi/domoticz/plugins/IKEA-Tradfri/twistd.pid \
      --python=/home/pi/domoticz/plugins/IKEA-Tradfri/tradfri.tac

User=pi
Group=pi

Restart=always

[Install]
WantedBy=multi-user.target
```

Because the fact I can start the plugin manually I don't think the problem is related to the Raspberry Pi or software.

**Comment by moroen** [comment]
You're service file appears to be correct. Though, using the ikea-tradfri command line utility is no longer recommended,  I suggest you take a look at the latest master version, which doesn't need a separate service...

**Comment by EvertJob** [comment]
I've allready thought about upgrading. I'm only a bit nervous off bricking my complete installation.

When installing the lastest master version will not work  (for what reason), the old commandline plugin is still working?

**Comment by moroen** [comment]
The recommended way to do the upgrade, is to stop the domoticz service, and make a copy of the entire domoticz directory, for instance to domoticz-test, then go to the plugin directory in this new folder, and pull the lastest master branch, which is the new pycoap version. Configure the plugin and start domoticz in this test-folder from the command line, then go to the hardware page and update the settings for IKEA-Tradfri.

When you're (hopefully) satisfied that the new version works, just stop domoticz, rename the original folder to something (for instance domoticz-old) and rename the domoticz-test folder to domoticz. 

It is possible to revert to the old version "in place" (git checkout legacy; git pull), but this is not recommended!
