### ISSUE TITLE
IKEA Tradfri gateway + Domoticz AND Home Assistant

### ISSUE THREAD

**Issue by bartplessers** [moroen/IKEA-Tradfri-plugin#97]
Hi

I have
- IKEA Tradfri gateway
- DOMOTICZ v4.10717 with IKEA Tradfri Plugin - version 0.7.3
- HOME ASSISTANT (hassio in docker) v0.104.3, with IKEA Tradfri integration

I noticed that I can **NOT** connect **both** addons to my IKEA hub.
It works... sometimes, but I have the feeling that the Domoticz plugin "locks" the connection so that hassio can not control my devices anymore.

Hass.io is responsive and shows changes in status immediatly.
But if I enable the Domoticz Tradfri plugin in domoticz, things are working well for a short while. After that, hass.io doesn't show any status changes.

In domoticz, I tried the different options for "observe changes" in the plugin settings, but no solution.

Does anybody has the same experience?
Is this a bug?

Kind regards,
Bart

**Comment by moroen** [comment]
Updated py3coap to version 0.8.0, should fix this. Closing issue, feel free to reopen if needed.
